// <auto-generated />
using API_LABB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_LABB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_LABB.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Alpint och längdskidor",
                            Title = "Skidåkning"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Webb- och apputveckling",
                            Title = "Programmering"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Laga mat från olika kulturer",
                            Title = "Matlagning"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Landskap och porträttfoto",
                            Title = "Fotografi"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Motionslöpning och tävling",
                            Title = "Löpning"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Spela och lyssna på musik",
                            Title = "Musik"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Skönlitteratur och facklitteratur",
                            Title = "Läsning"
                        },
                        new
                        {
                            Id = 8,
                            Description = "PC- och konsolspel",
                            Title = "Gaming"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Rörlighet och mindfulness",
                            Title = "Yoga"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Landsvägscykling och MTB",
                            Title = "Cykling"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Inomhus- och utomhusklättring",
                            Title = "Klättring"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Se och diskutera film",
                            Title = "Filmklubb"
                        });
                });

            modelBuilder.Entity("API_LABB.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 1,
                            Label = "SkiStar",
                            PersonId = 1,
                            Url = "https://skistar.com"
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 2,
                            Label = "Annas GitHub",
                            PersonId = 1,
                            Url = "https://github.com/anna"
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 5,
                            Label = "Runners World",
                            PersonId = 1,
                            Url = "https://runnersworld.com"
                        },
                        new
                        {
                            Id = 4,
                            InterestId = 2,
                            Label = "Stack Overflow",
                            PersonId = 2,
                            Url = "https://stackoverflow.com"
                        },
                        new
                        {
                            Id = 5,
                            InterestId = 3,
                            Label = "Allt om Mat",
                            PersonId = 2,
                            Url = "https://alltommat.se"
                        },
                        new
                        {
                            Id = 6,
                            InterestId = 8,
                            Label = "Steam",
                            PersonId = 2,
                            Url = "https://store.steampowered.com"
                        },
                        new
                        {
                            Id = 7,
                            InterestId = 4,
                            Label = "500px",
                            PersonId = 3,
                            Url = "https://500px.com"
                        },
                        new
                        {
                            Id = 8,
                            InterestId = 7,
                            Label = "Goodreads",
                            PersonId = 3,
                            Url = "https://goodreads.com"
                        },
                        new
                        {
                            Id = 9,
                            InterestId = 9,
                            Label = "Yoga Journal",
                            PersonId = 3,
                            Url = "https://yogajournal.com"
                        },
                        new
                        {
                            Id = 10,
                            InterestId = 5,
                            Label = "Strava",
                            PersonId = 4,
                            Url = "https://strava.com"
                        },
                        new
                        {
                            Id = 11,
                            InterestId = 10,
                            Label = "Cycling Weekly",
                            PersonId = 4,
                            Url = "https://cyclingweekly.com"
                        },
                        new
                        {
                            Id = 12,
                            InterestId = 11,
                            Label = "The BMC",
                            PersonId = 4,
                            Url = "https://thebmc.co.uk"
                        },
                        new
                        {
                            Id = 13,
                            InterestId = 6,
                            Label = "Spotify",
                            PersonId = 5,
                            Url = "https://spotify.com"
                        },
                        new
                        {
                            Id = 14,
                            InterestId = 7,
                            Label = "Bokus",
                            PersonId = 5,
                            Url = "https://bokus.com"
                        },
                        new
                        {
                            Id = 15,
                            InterestId = 12,
                            Label = "Filmtipset",
                            PersonId = 5,
                            Url = "https://filmtipset.se"
                        },
                        new
                        {
                            Id = 16,
                            InterestId = 2,
                            Label = "LeetCode",
                            PersonId = 6,
                            Url = "https://leetcode.com"
                        },
                        new
                        {
                            Id = 17,
                            InterestId = 8,
                            Label = "Twitch",
                            PersonId = 6,
                            Url = "https://twitch.tv"
                        },
                        new
                        {
                            Id = 18,
                            InterestId = 11,
                            Label = "Climbing Wall",
                            PersonId = 6,
                            Url = "https://climbingwall.com"
                        },
                        new
                        {
                            Id = 19,
                            InterestId = 3,
                            Label = "Köket.se",
                            PersonId = 7,
                            Url = "https://koket.se"
                        },
                        new
                        {
                            Id = 20,
                            InterestId = 9,
                            Label = "Down Dog",
                            PersonId = 7,
                            Url = "https://downdogapp.com"
                        },
                        new
                        {
                            Id = 21,
                            InterestId = 12,
                            Label = "IMDb",
                            PersonId = 7,
                            Url = "https://imdb.com"
                        },
                        new
                        {
                            Id = 22,
                            InterestId = 1,
                            Label = "Skidresor.se",
                            PersonId = 8,
                            Url = "https://skidresor.se"
                        },
                        new
                        {
                            Id = 23,
                            InterestId = 4,
                            Label = "Unsplash",
                            PersonId = 8,
                            Url = "https://unsplash.com"
                        },
                        new
                        {
                            Id = 24,
                            InterestId = 10,
                            Label = "BikeRadar",
                            PersonId = 8,
                            Url = "https://bikeradar.com"
                        },
                        new
                        {
                            Id = 25,
                            InterestId = 5,
                            Label = "Garmin Connect",
                            PersonId = 9,
                            Url = "https://garmin.com"
                        },
                        new
                        {
                            Id = 26,
                            InterestId = 6,
                            Label = "SoundCloud",
                            PersonId = 9,
                            Url = "https://soundcloud.com"
                        },
                        new
                        {
                            Id = 27,
                            InterestId = 7,
                            Label = "Adlibris",
                            PersonId = 9,
                            Url = "https://adlibris.com"
                        },
                        new
                        {
                            Id = 28,
                            InterestId = 2,
                            Label = "Microsoft Docs",
                            PersonId = 10,
                            Url = "https://docs.microsoft.com"
                        },
                        new
                        {
                            Id = 29,
                            InterestId = 8,
                            Label = "IGN",
                            PersonId = 10,
                            Url = "https://ign.com"
                        },
                        new
                        {
                            Id = 30,
                            InterestId = 12,
                            Label = "Letterboxd",
                            PersonId = 10,
                            Url = "https://letterboxd.com"
                        });
                });

            modelBuilder.Entity("API_LABB.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Anna Svensson",
                            Phone = "070-123 45 67"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Erik Lindqvist",
                            Phone = "073-987 65 43"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Maria Johansson",
                            Phone = "076-555 12 34"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Oskar Bergström",
                            Phone = "072-444 98 76"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lina Karlsson",
                            Phone = "070-333 21 09"
                        },
                        new
                        {
                            Id = 6,
                            Name = "David Nilsson",
                            Phone = "073-222 87 65"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sara Eriksson",
                            Phone = "076-111 54 32"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Johan Petersson",
                            Phone = "072-999 43 21"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Emma Lundgren",
                            Phone = "070-888 76 54"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Felix Magnusson",
                            Phone = "073-777 65 43"
                        });
                });

            modelBuilder.Entity("API_LABB.Models.PersonInterest", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("PersonId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("PersonInterests");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            InterestId = 1
                        },
                        new
                        {
                            PersonId = 1,
                            InterestId = 2
                        },
                        new
                        {
                            PersonId = 1,
                            InterestId = 5
                        },
                        new
                        {
                            PersonId = 2,
                            InterestId = 2
                        },
                        new
                        {
                            PersonId = 2,
                            InterestId = 3
                        },
                        new
                        {
                            PersonId = 2,
                            InterestId = 8
                        },
                        new
                        {
                            PersonId = 3,
                            InterestId = 4
                        },
                        new
                        {
                            PersonId = 3,
                            InterestId = 7
                        },
                        new
                        {
                            PersonId = 3,
                            InterestId = 9
                        },
                        new
                        {
                            PersonId = 4,
                            InterestId = 5
                        },
                        new
                        {
                            PersonId = 4,
                            InterestId = 10
                        },
                        new
                        {
                            PersonId = 4,
                            InterestId = 11
                        },
                        new
                        {
                            PersonId = 5,
                            InterestId = 6
                        },
                        new
                        {
                            PersonId = 5,
                            InterestId = 7
                        },
                        new
                        {
                            PersonId = 5,
                            InterestId = 12
                        },
                        new
                        {
                            PersonId = 6,
                            InterestId = 2
                        },
                        new
                        {
                            PersonId = 6,
                            InterestId = 8
                        },
                        new
                        {
                            PersonId = 6,
                            InterestId = 11
                        },
                        new
                        {
                            PersonId = 7,
                            InterestId = 3
                        },
                        new
                        {
                            PersonId = 7,
                            InterestId = 9
                        },
                        new
                        {
                            PersonId = 7,
                            InterestId = 12
                        },
                        new
                        {
                            PersonId = 8,
                            InterestId = 1
                        },
                        new
                        {
                            PersonId = 8,
                            InterestId = 4
                        },
                        new
                        {
                            PersonId = 8,
                            InterestId = 10
                        },
                        new
                        {
                            PersonId = 9,
                            InterestId = 5
                        },
                        new
                        {
                            PersonId = 9,
                            InterestId = 6
                        },
                        new
                        {
                            PersonId = 9,
                            InterestId = 7
                        },
                        new
                        {
                            PersonId = 10,
                            InterestId = 2
                        },
                        new
                        {
                            PersonId = 10,
                            InterestId = 8
                        },
                        new
                        {
                            PersonId = 10,
                            InterestId = 12
                        });
                });

            modelBuilder.Entity("API_LABB.Models.Link", b =>
                {
                    b.HasOne("API_LABB.Models.Interest", "Interest")
                        .WithMany("Links")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_LABB.Models.Person", "Person")
                        .WithMany("Links")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("API_LABB.Models.PersonInterest", b =>
                {
                    b.HasOne("API_LABB.Models.Interest", "Interest")
                        .WithMany("PersonInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_LABB.Models.Person", "Person")
                        .WithMany("PersonInterests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("API_LABB.Models.Interest", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("PersonInterests");
                });

            modelBuilder.Entity("API_LABB.Models.Person", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("PersonInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
